@startuml

package ImageCapture
{
    interface ICapture
    {
        # curFrame : cv::Mat
        # active : bool
        # thread : std::thread
        # updateMutex : std::mutex
        # ROI : cv::Point[4]
        + //setRoi(roi : const cv::Point[4]) : void//
        + //getFrame() : cv::Mat//
        + //stop() : void//
        - //update() : void//
    }

    class Capture
    {
        - cap : cv::VideoCapture
        + Capture(device:int)
    }

    class CameraConfig
    {
        - file : std::ifstream
        + CameraConfig(filepath : const string&)
        + getValue(key : const string&) : string
    }
}

ICapture <|. Capture
Capture -> "1" CameraConfig

@enduml