@startuml

package ImageDrawer
{
    class ColorRGBInt <<struct>>
    {
        + r : int
        + b : int
        + g : int
    }

    class ColorRGBAInt <<struct>>
    {
        + a : int
    }

    interface IImageDrawer
    {
        + setDrawColor(color : const ColorRGBAInt&) : void
        + setDrawColor(color : const ColorRGBInt&) : void
        + setBackground(color : const ColorRGBInt&) : void
        + drawCircle(center : const cv::Point&, radius : double, thickness : int) : void
        + drawLine(pointA : const cv::Poin&t, pointB : const cv::Point&, thickness : int) : void
    }

    class CairoDrawer
    {
        - fbp : char*
        - cairoContext : cairo_t*
        - cairoSurface : cairo_surface_t*
        - screenWidth : int
        - screenHeight : int
        - setTty(device : string, mode : int) : bool
        + CairoDrawer(framebuffer : string, terminal : string, format : cairo_format_t)
    }
}

IImageDrawer .> ColorRGBInt
IImageDrawer .> ColorRGBAInt

IImageDrawer <|.. CairoDrawer

ColorRGBInt <|-- ColorRGBAInt

@enduml