@startuml 
header
Design class diagram BoundaryDetector
endheader

package Detector{
    Class Line<<Struct>>{
        a : double
        b : double
        c : double
        Line(a : double, b : double, c : double)
    }
    Class BoundaryDetector{
        - src : cv::Mat
        - drawing : cv::Mat
        - threshold : cv::Mat
        - hsv : cv::Mat
        + run(argc : int, argv : char[]*) :void
        - calculateLine(lines : vector<Line>*, pointA : const cv::Point&, pointB : const cv::Point&) : void
        - calculateIntersects(lines : const vector<Line>&)
    }
}

BoundaryDetector ..> Line

@enduml