@startuml

left to right direction

rectangle pool as "Pool aid" {
    
    usecase start as "1. Start system"

    usecase visualize_ball as "5. Visualize cue ball"

    usecase visualize_trajectory as "6. Visualize trajectory"

    usecase detect_balls as "2. Detect balls"

    usecase pool_cue as "3. Present cue"

    usecase detect_cue as "8. Detect cue"

    usecase calc_trajectory as "7. Calculate trajectory"

    usecase stop as "4. Stop system"
}

actor Player

Player --> start

Player --> pool_cue

detect_cue <. calc_trajectory : "extend"

calc_trajectory <.  visualize_trajectory : "extend"

detect_balls <.. visualize_ball : "extend"

pool_cue ..> detect_cue : "include"

Player --> stop


@enduml